/**
 * Outcome Comment Type Definitions
 * Maps to backend API OutcomeComment entity
 * Backend API Reference: http://localhost:3000/api-docs/ui
 *
 * IMPORTANT NOTES:
 * - id is string (MongoDB ObjectId), updated from number
 * - subjectId is string (MongoDB ObjectId), updated from number
 * - Field names are camelCase (createdAt), not snake_case (created_at)
 * - Timestamps are ISO 8601 strings
 * - Score ranges (lowerRange, upperRange) remain numeric
 *
 * Related: TD-002 (OutcomeComment classId → subjectId Migration)
 * Change: classId → subjectId to align with Subject-based architecture
 * Migration: API ID fields migrated from integer to string (MongoDB ObjectIds)
 */

/**
 * Outcome Comment entity representing a score-based comment on subject outcomes
 * Returned by: GET /outcome-comment, GET /outcome-comment/:id, POST /outcome-comment, PUT /outcome-comment/:id
 */
export interface OutcomeComment {
  /** Unique identifier (MongoDB ObjectId string) - Auto-generated by backend */
  id: string
  /** Upper score range for this comment (numeric score boundary) */
  upperRange: number
  /** Lower score range for this comment (numeric score boundary) */
  lowerRange: number
  /** Comment text */
  comment: string
  /** Associated subject ID (MongoDB ObjectId string, references Subject.id) - Changed from classId */
  subjectId: string
  /** User ID of the comment creator (Auth0 user identifier) */
  userId: string
  /** Creation timestamp (ISO 8601) - Auto-generated, immutable */
  createdAt: string
  /** Last update timestamp (ISO 8601) - Auto-updated by backend */
  updatedAt: string
}

/**
 * Request payload for creating a new outcome comment
 * Used by: POST /outcome-comment
 */
export interface CreateOutcomeCommentRequest {
  /** Upper score range for this comment (numeric score boundary) - Required */
  upperRange: number
  /** Lower score range for this comment (numeric score boundary) - Required */
  lowerRange: number
  /** Comment text - Required */
  comment: string
  /** Associated subject ID (MongoDB ObjectId string) - Required (changed from classId) */
  subjectId: string
}

/**
 * Request payload for updating an existing outcome comment
 * Used by: PUT /outcome-comment/:id
 */
export interface UpdateOutcomeCommentRequest {
  /** Upper score range for this comment - Required */
  upperRange: number
  /** Lower score range for this comment - Required */
  lowerRange: number
  /** Comment text - Required */
  comment: string
}
